name: CD
on:
  push:
    branches:
      - main
      - beta
  workflow_dispatch:
jobs:
    CD:
        runs-on: ubuntu-latest

        permissions:
          contents: write
          id-token: write
          pull-requests: write
    
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
            with:
              node-version-file: ".nvmrc"
              cache: yarn

          - name: Install
            run: yarn install --frozen-lockfile

          - name: Build
            run: yarn build

          - name: Test
            run: yarn test

          - name: Create Release Pull Request or Publish to npm
            id: changesets
            uses: changesets/action@v1
            with:
              publish: npx changeset publish
              title: "🦋 Release package updates"
              commit: "Bump package version"
    
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
